apiVersion: batch/v1
kind: CronJob
metadata:
  name: acme-certs-job
spec:
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
          - name: lego-files
            persistentVolumeClaim:
              claimName: lego-files-pvc-lh