apiVersion: batch/v1
kind: CronJob
metadata:
  name: acme-certs-job
spec:
  schedule: "0 0 * * *"  # This cron expression runs the job once a day at midnight
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: acme-certs-sa
          containers:
          - name: acme-certs-job
            imagePullPolicy: Always
            image: ghcr.io/pajikos/acme-certs-job:latest
            envFrom:
            - configMapRef:
                name: environment-variables
            volumeMounts:
            - name: lego-files
              mountPath: /app/lego-files
            - name: domains-config
              mountPath: /app/domains.config
              subPath: domains.config
          restartPolicy: OnFailure
          volumes:
          - name: lego-files
            persistentVolumeClaim:
              claimName: lego-files-pvc
          - name: domains-config
            configMap:
              name: domains-config
