apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acme-certs-rolebinding
subjects:
  - kind: ServiceAccount
    name: acme-certs-sa
roleRef:
  kind: Role
  name: acme-certs-role
  apiGroup: rbac.authorization.k8s.io
